_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 23
                - 55
            "4": 3.12.0
            "5": 0.18.2
            "8":
                - 3
                - 5
            "12": 0.18.2
            "13": windows-amd64
